import {Platform, StyleSheet} from 'react-native';

const cardShadow = Platform.select({
  android: {elevation: 2},
  ios: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  default: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
  },
  pageTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111111',
    marginBottom: 16,
  },
  filterCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 24,
    ...cardShadow,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
  },
  yearField: {
    minWidth: 110,
    marginRight: 16,
    marginBottom: 8,
  },
  yearLabel: {
    fontSize: 12,
    color: '#7A7A7A',
    marginBottom: 2,
  },
  yearInput: {
    minWidth: 96,
    borderBottomWidth: 1,
    borderBottomColor: '#D4D4D8',
    paddingVertical: 2,
    paddingHorizontal: 0,
    fontSize: 16,
    color: '#111111',
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111111',
    borderRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 11,
    marginRight: 8,
    marginBottom: 8,
    minHeight: 42,
    ...cardShadow,
  },
  filterButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#F4C400',
    marginRight: 8,
    textTransform: 'uppercase',
  },
  clearButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    backgroundColor: '#111111',
    marginBottom: 8,
    ...cardShadow,
  },
  errorText: {
    marginBottom: 12,
    color: '#B91C1C',
    fontSize: 13,
  },
  monthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
  },
  monthCardContainer: {
    paddingHorizontal: 8,
    marginBottom: 16,
  },
  monthCard: {
    flex: 1,
    minHeight: 278,
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    ...cardShadow,
  },
  monthTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111111',
    marginBottom: 16,
  },
  metricBox: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#DCDDDF',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 26,
  },
  metricLabel: {
    fontSize: 13,
    color: '#8B8B8B',
  },
  metricAction: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#F4C400',
    alignItems: 'center',
    justifyContent: 'center',
  },
  totalsBlock: {
    marginTop: 2,
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  totalLabel: {
    fontSize: 13,
  },
  totalValue: {
    fontSize: 13,
    fontWeight: '600',
  },
  textGreen: {
    color: '#22AA46',
  },
  textRed: {
    color: '#FF3B30',
  },
  bold: {
    fontWeight: '700',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyStateTitle: {
    marginTop: 12,
    fontSize: 18,
    fontWeight: '700',
    color: '#111111',
  },
  emptyStateText: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: '#6B7280',
    textAlign: 'center',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modalCard: {
    width: '100%',
    maxWidth: 640,
    maxHeight: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 16,
    ...cardShadow,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111111',
    marginBottom: 12,
  },
  modalScroll: {
    flexGrow: 0,
  },
  modalScrollContent: {
    paddingBottom: 4,
  },
  modalSection: {
    marginBottom: 14,
  },
  modalSectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111111',
    marginBottom: 6,
  },
  modalText: {
    fontSize: 14,
    color: '#374151',
    marginBottom: 4,
  },
  modalEmptyText: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 4,
  },
  modalButton: {
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#111111',
    borderRadius: 4,
    paddingVertical: 12,
  },
  modalButtonText: {
    color: '#F4C400',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 14,
    color: '#6B7280',
  },
});

export default styles;
